package rs.ac.bg.fon.ai.biblioteka_server.forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;

public class ServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnPokreni = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        btnZaustavi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUlogovani = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmServer = new javax.swing.JMenu();
        jmiPodesavanja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPokreni.setBackground(new java.awt.Color(76, 117, 95));
        btnPokreni.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnPokreni.setForeground(new java.awt.Color(255, 255, 255));
        btnPokreni.setText("Pokreni server");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStatus.setText("Status: Server je zaustavljen.");

        btnZaustavi.setBackground(new java.awt.Color(171, 59, 58));
        btnZaustavi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnZaustavi.setForeground(new java.awt.Color(255, 255, 255));
        btnZaustavi.setText("Zaustavi server");

        tblUlogovani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUlogovani.setSelectionBackground(new java.awt.Color(250, 227, 175));
        jScrollPane1.setViewportView(tblUlogovani);

        jmServer.setText("Server");

        jmiPodesavanja.setText("Podesavanja");
        jmServer.add(jmiPodesavanja);

        jMenuBar1.add(jmServer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPokreni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnZaustavi))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblStatus)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>                        

    public JButton getBtnPokreni() {
        return btnPokreni;
    }

    public JButton getBtnZaustavi() {
        return btnZaustavi;
    }

    public JLabel getLblStatus() {
        return lblStatus;
    }

    public JTable getTblUlogovani() {
        return tblUlogovani;
    }
   
    public void jmiPodesavanjaAddActionListener(ActionListener actionListener) {
        jmiPodesavanja.addActionListener(actionListener);
    }
    
    public void btnPokreniAddActionListener(ActionListener actionListener) {
        btnPokreni.addActionListener(actionListener);
    }
    
    public void btnZaustaviAddActionListener(ActionListener actionListener) {
        btnZaustavi.addActionListener(actionListener);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmServer;
    private javax.swing.JMenuItem jmiPodesavanja;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblUlogovani;
    // End of variables declaration                   
}
