package rs.ac.bg.fon.ai.biblioteka_klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    ImageIcon slicica = new ImageIcon("library.png");
    
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
        lblSlika.setIcon(slicica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        txtBibliotekar = new javax.swing.JTextField();
        lblSlika = new javax.swing.JLabel();
        btnKraj = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiDodajKnjigu = new javax.swing.JMenuItem();
        jmiPregledKnjiga = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiDodajClana = new javax.swing.JMenuItem();
        jmiPregledClanova = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiKreirajPozajmicu = new javax.swing.JMenuItem();
        jmiPregledPozajmica = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bibliotekar:");

        txtBibliotekar.setEditable(false);

        lblSlika.setText(" ");

        btnKraj.setText("Kraj rada");
        btnKraj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 59, 58)));

        jMenu2.setText("Knjige");

        jmiDodajKnjigu.setText("Dodaj novu knjigu");
        jMenu2.add(jmiDodajKnjigu);

        jmiPregledKnjiga.setText("Pregled knjiga");
        jMenu2.add(jmiPregledKnjiga);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Clanovi");

        jmiDodajClana.setText("Dodaj novog clana");
        jMenu3.add(jmiDodajClana);

        jmiPregledClanova.setText("Pregled clanova");
        jMenu3.add(jmiPregledClanova);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pozajmice");

        jmiKreirajPozajmicu.setText("Kreiraj pozajmicu");
        jMenu4.add(jmiKreirajPozajmicu);

        jmiPregledPozajmica.setText("Pregled pozajmica");
        jMenu4.add(jmiPregledPozajmica);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBibliotekar, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBibliotekar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(lblSlika)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    public JTextField getTxtBibliotekar() {
        return txtBibliotekar;
    }
    
    public void jmiDodajClanaAddActionListener(ActionListener actionListener) {
        jmiDodajClana.addActionListener(actionListener);
    }
    
    public void jmiPregledClanovaAddActionListener(ActionListener actionListener) {
        jmiPregledClanova.addActionListener(actionListener);
    }
    
    public void jmiDodajKnjiguAddActionListener(ActionListener actionListener) {
        jmiDodajKnjigu.addActionListener(actionListener);
    }
    
    public void jmiPregledKnjigaaAddActionListener(ActionListener actionListener) {
        jmiPregledKnjiga.addActionListener(actionListener);
    }
    
    public void jmiKreirajPozajmicuAddActionListener(ActionListener actionListener) {
        jmiKreirajPozajmicu.addActionListener(actionListener);
    }
    
    public void jmiPregledPozajmicaAddActionListener(ActionListener actionListener) {
        jmiPregledPozajmica.addActionListener(actionListener);
    }
    
    public void btnKrajAddActionListener(ActionListener actionListener) {
        btnKraj.addActionListener(actionListener);
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnKraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiDodajClana;
    private javax.swing.JMenuItem jmiDodajKnjigu;
    private javax.swing.JMenuItem jmiKreirajPozajmicu;
    private javax.swing.JMenuItem jmiPregledClanova;
    private javax.swing.JMenuItem jmiPregledKnjiga;
    private javax.swing.JMenuItem jmiPregledPozajmica;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JTextField txtBibliotekar;
    // End of variables declaration                   
}
