package rs.ac.bg.fon.ai.biblioteka_klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class PregledPozajmicaForma extends javax.swing.JDialog {

    /**
     * Creates new form PregledPozajmicaForma
     */
    public PregledPozajmicaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClanovi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPrikaziPozajmice = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPozajmice = new javax.swing.JTable();
        btnDetaljiPozajmice = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnResetujPretragu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnVratiKnjigu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSacuvajPromene = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNapomena = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled pozajmica");

        tblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClanovi.setSelectionBackground(new java.awt.Color(250, 227, 175));
        jScrollPane1.setViewportView(tblClanovi);

        jLabel1.setText("Odabir clana:");

        btnPrikaziPozajmice.setBackground(new java.awt.Color(76, 117, 95));
        btnPrikaziPozajmice.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikaziPozajmice.setText("Prikazi pozajmice za clana");

        jLabel2.setText("Pozajmice clana:");

        tblPozajmice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPozajmice.setSelectionBackground(new java.awt.Color(250, 227, 175));
        jScrollPane2.setViewportView(tblPozajmice);

        btnDetaljiPozajmice.setBackground(new java.awt.Color(76, 117, 95));
        btnDetaljiPozajmice.setForeground(new java.awt.Color(255, 255, 255));
        btnDetaljiPozajmice.setText("Detalji pozajmice");

        jLabel3.setText("Ime clana: ");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 117, 95)));
        btnPretrazi.setPreferredSize(new java.awt.Dimension(52, 40));

        btnResetujPretragu.setText("Resetuj pretragu");
        btnResetujPretragu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 117, 95)));
        btnResetujPretragu.setPreferredSize(new java.awt.Dimension(111, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke pozajmice"));

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStavke.setSelectionBackground(new java.awt.Color(250, 227, 175));
        jScrollPane3.setViewportView(tblStavke);

        btnVratiKnjigu.setText("Vrati knjigu");
        btnVratiKnjigu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 117, 95)));
        btnVratiKnjigu.setPreferredSize(new java.awt.Dimension(77, 40));

        jLabel4.setText("Napomena:");

        btnSacuvajPromene.setBackground(new java.awt.Color(76, 117, 95));
        btnSacuvajPromene.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajPromene.setText("Sacuvaj promene");

        txtNapomena.setColumns(20);
        txtNapomena.setRows(5);
        jScrollPane4.setViewportView(txtNapomena);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnVratiKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnSacuvajPromene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVratiKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvajPromene, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnResetujPretragu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(btnPrikaziPozajmice))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(btnDetaljiPozajmice)))
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnResetujPretragu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrikaziPozajmice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetaljiPozajmice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    public JTable getTblClanovi() {
        return tblClanovi;
    }

    public JTable getTblPozajmice() {
        return tblPozajmice;
    }

    public JTextField getTxtIme() {
        return txtIme;
    }

    public JButton getBtnSacuvajPromene() {
        return btnSacuvajPromene;
    }

    public JButton getBtnVratiKnjigu() {
        return btnVratiKnjigu;
    }

    public JTable getTblStavke() {
        return tblStavke;
    }

    public JTextArea getTxtNapomena() {
        return txtNapomena;
    }
    
    public void btnPretraziAddActionListener(ActionListener actionListener) {
        btnPretrazi.addActionListener(actionListener);
    }
    
    public void btnResetujPretraguAddActionListener(ActionListener actionListener) {
        btnResetujPretragu.addActionListener(actionListener);
    }
    
    public void btnPrikaziPozajmiceAddActionListener(ActionListener actionListener) {
        btnPrikaziPozajmice.addActionListener(actionListener);
    }
    
    public void btnDetaljiPozajmiceAddActionListener(ActionListener actionListener) {
        btnDetaljiPozajmice.addActionListener(actionListener);
    }
    
    public void btnVratiKnjiguAddActionListener(ActionListener actionListener) {
        btnVratiKnjigu.addActionListener(actionListener);
    }
    
    public void btnSacuvajPromenePozajmiceAddActionListener(ActionListener actionListener) {
        btnSacuvajPromene.addActionListener(actionListener);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDetaljiPozajmice;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziPozajmice;
    private javax.swing.JButton btnResetujPretragu;
    private javax.swing.JButton btnSacuvajPromene;
    private javax.swing.JButton btnVratiKnjigu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblClanovi;
    private javax.swing.JTable tblPozajmice;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextArea txtNapomena;
    // End of variables declaration                   
}

