package rs.ac.bg.fon.ai.biblioteka_klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

public class PregledKnjigaForma extends javax.swing.JDialog {

    /**
     * Creates new form PregledKnjigaForma
     */
    public PregledKnjigaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKnjige = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNaslov = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbbAutori = new javax.swing.JComboBox<>();
        btnPretrazi = new javax.swing.JButton();
        btnResetujPretragu = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled knjiga");

        tblKnjige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKnjige.setSelectionBackground(new java.awt.Color(250, 227, 175));
        jScrollPane1.setViewportView(tblKnjige);

        jLabel1.setText("Naslov:");

        jLabel2.setText("Autor:");

        cbbAutori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 117, 95)));

        btnResetujPretragu.setText("Resetuj pretragu");
        btnResetujPretragu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 117, 95)));

        btnDetalji.setBackground(new java.awt.Color(76, 117, 95));
        btnDetalji.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalji.setText("Detalji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbAutori, 0, 277, Short.MAX_VALUE)
                            .addComponent(txtNaslov))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetujPretragu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbAutori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetujPretragu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>                        

    public JButton getBtnDetalji() {
        return btnDetalji;
    }

    public void setBtnDetalji(JButton btnDetalji) {
        this.btnDetalji = btnDetalji;
    }

    public JButton getBtnPretrazi() {
        return btnPretrazi;
    }

    public void setBtnPretrazi(JButton btnPretrazi) {
        this.btnPretrazi = btnPretrazi;
    }

    public JButton getBtnResetujPretragu() {
        return btnResetujPretragu;
    }

    public void setBtnResetujPretragu(JButton btnResetujPretragu) {
        this.btnResetujPretragu = btnResetujPretragu;
    }

    public JComboBox<String> getCbbAutor() {
        return cbbAutori;
    }

    public void setCbbAutor(JComboBox<String> cbbAutor) {
        this.cbbAutori = cbbAutor;
    }

    public JTable getTblKnjige() {
        return tblKnjige;
    }

    public void setTblKnjige(JTable tblKnjige) {
        this.tblKnjige = tblKnjige;
    }

    public JTextField getTxtNaslov() {
        return txtNaslov;
    }

    public void setTxtNaslov(JTextField txtNaslov) {
        this.txtNaslov = txtNaslov;
    }
    
    public void btnDetaljiAddActionListener(ActionListener actionListener) {
        btnDetalji.addActionListener(actionListener);
    }
    
    public void btnPretraziAddActionListener(ActionListener actionListener) {
        btnPretrazi.addActionListener(actionListener);
    }
    
    public void btnResetujPretraguAddActionListener(ActionListener actionListener) {
        btnResetujPretragu.addActionListener(actionListener);
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnResetujPretragu;
    private javax.swing.JComboBox<String> cbbAutori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKnjige;
    private javax.swing.JTextField txtNaslov;
    // End of variables declaration                   
}

